name : github actions demo
on : push
jobs : explore-github-actions
runs_on : ubunto-latest
steps :

- name:  Print the triggering event

run :  echo "The job was triggered by ${{ github.event_name
 
- name: Print the OS of the runner
 
run : echo " This job is running on a ${{ runner.os Y} server "

- name:  Print the branch name that the workflow runs on

run :  echo "3) The name Of your branch is ${{ github.ref ) } .

- name:  Check out repository code action

uses: actions/checkout@v4

- run:  echo " Cloning The ${{ github. repository repository

- name:  List files in the repository

run :  Is ${{ github.workspace











